/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  type ParsedDepositInstruction,
  type ParsedExternalTransferInstruction,
  type ParsedInitializeInstruction,
  type ParsedInternalTransferInstruction,
  type ParsedWithdrawInstruction,
} from "../instructions";

export const ONCHAIN_PROGRAM_ADDRESS =
  "CJ5ysHVQzRNQqSDoPekKhhyq1i11Wn15WbUhKRZYScqg" as Address<"CJ5ysHVQzRNQqSDoPekKhhyq1i11Wn15WbUhKRZYScqg">;

export enum OnchainAccount {
  UserAccount,
}

export function identifyOnchainAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): OnchainAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([211, 33, 136, 16, 186, 110, 242, 127]),
      ),
      0,
    )
  ) {
    return OnchainAccount.UserAccount;
  }
  throw new Error(
    "The provided account could not be identified as a onchain account.",
  );
}

export enum OnchainInstruction {
  Deposit,
  ExternalTransfer,
  Initialize,
  InternalTransfer,
  Withdraw,
}

export function identifyOnchainInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): OnchainInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([242, 35, 198, 137, 82, 225, 242, 182]),
      ),
      0,
    )
  ) {
    return OnchainInstruction.Deposit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([11, 179, 85, 190, 61, 53, 105, 169]),
      ),
      0,
    )
  ) {
    return OnchainInstruction.ExternalTransfer;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237]),
      ),
      0,
    )
  ) {
    return OnchainInstruction.Initialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([56, 217, 60, 137, 252, 221, 185, 114]),
      ),
      0,
    )
  ) {
    return OnchainInstruction.InternalTransfer;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([183, 18, 70, 156, 148, 109, 161, 34]),
      ),
      0,
    )
  ) {
    return OnchainInstruction.Withdraw;
  }
  throw new Error(
    "The provided instruction could not be identified as a onchain instruction.",
  );
}

export type ParsedOnchainInstruction<
  TProgram extends string = "CJ5ysHVQzRNQqSDoPekKhhyq1i11Wn15WbUhKRZYScqg",
> =
  | ({
      instructionType: OnchainInstruction.Deposit;
    } & ParsedDepositInstruction<TProgram>)
  | ({
      instructionType: OnchainInstruction.ExternalTransfer;
    } & ParsedExternalTransferInstruction<TProgram>)
  | ({
      instructionType: OnchainInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: OnchainInstruction.InternalTransfer;
    } & ParsedInternalTransferInstruction<TProgram>)
  | ({
      instructionType: OnchainInstruction.Withdraw;
    } & ParsedWithdrawInstruction<TProgram>);
