/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { ONCHAIN_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const DEPOSIT_DISCRIMINATOR = new Uint8Array([
  242, 35, 198, 137, 82, 225, 242, 182,
]);

export function getDepositDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(DEPOSIT_DISCRIMINATOR);
}

export type DepositInstruction<
  TProgram extends string = typeof ONCHAIN_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountUserAccountPda extends string | AccountMeta<string> = string,
  TAccountUserAta extends string | AccountMeta<string> = string,
  TAccountLevMint extends string | AccountMeta<string> = string,
  TAccountMintAuthorityPda extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountUserAccountPda extends string
        ? WritableAccount<TAccountUserAccountPda>
        : TAccountUserAccountPda,
      TAccountUserAta extends string
        ? WritableAccount<TAccountUserAta>
        : TAccountUserAta,
      TAccountLevMint extends string
        ? WritableAccount<TAccountLevMint>
        : TAccountLevMint,
      TAccountMintAuthorityPda extends string
        ? ReadonlyAccount<TAccountMintAuthorityPda>
        : TAccountMintAuthorityPda,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type DepositInstructionData = {
  discriminator: ReadonlyUint8Array;
  index: number;
  amount: bigint;
};

export type DepositInstructionDataArgs = {
  index: number;
  amount: number | bigint;
};

export function getDepositInstructionDataEncoder(): FixedSizeEncoder<DepositInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["index", getU8Encoder()],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: DEPOSIT_DISCRIMINATOR }),
  );
}

export function getDepositInstructionDataDecoder(): FixedSizeDecoder<DepositInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["index", getU8Decoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getDepositInstructionDataCodec(): FixedSizeCodec<
  DepositInstructionDataArgs,
  DepositInstructionData
> {
  return combineCodec(
    getDepositInstructionDataEncoder(),
    getDepositInstructionDataDecoder(),
  );
}

export type DepositAsyncInput<
  TAccountUser extends string = string,
  TAccountUserAccountPda extends string = string,
  TAccountUserAta extends string = string,
  TAccountLevMint extends string = string,
  TAccountMintAuthorityPda extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** The user authorizes the deposit into one of their PDAs. */
  user: TransactionSigner<TAccountUser>;
  /** PDA that owns the destination ATA. */
  userAccountPda: Address<TAccountUserAccountPda>;
  /** Destination ATA for this subaccount. */
  userAta?: Address<TAccountUserAta>;
  /** Mint for LEV token. */
  levMint: Address<TAccountLevMint>;
  /** Program-derived mint authority PDA. */
  mintAuthorityPda?: Address<TAccountMintAuthorityPda>;
  tokenProgram?: Address<TAccountTokenProgram>;
  index: DepositInstructionDataArgs["index"];
  amount: DepositInstructionDataArgs["amount"];
};

export async function getDepositInstructionAsync<
  TAccountUser extends string,
  TAccountUserAccountPda extends string,
  TAccountUserAta extends string,
  TAccountLevMint extends string,
  TAccountMintAuthorityPda extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ONCHAIN_PROGRAM_ADDRESS,
>(
  input: DepositAsyncInput<
    TAccountUser,
    TAccountUserAccountPda,
    TAccountUserAta,
    TAccountLevMint,
    TAccountMintAuthorityPda,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  DepositInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUserAccountPda,
    TAccountUserAta,
    TAccountLevMint,
    TAccountMintAuthorityPda,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ONCHAIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    userAccountPda: { value: input.userAccountPda ?? null, isWritable: true },
    userAta: { value: input.userAta ?? null, isWritable: true },
    levMint: { value: input.levMint ?? null, isWritable: true },
    mintAuthorityPda: {
      value: input.mintAuthorityPda ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.userAta.value) {
    accounts.userAta.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.userAccountPda.value),
        ),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.levMint.value)),
      ],
    });
  }
  if (!accounts.mintAuthorityPda.value) {
    accounts.mintAuthorityPda.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([109, 105, 110, 116, 45, 97, 117, 116, 104]),
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.userAccountPda),
      getAccountMeta(accounts.userAta),
      getAccountMeta(accounts.levMint),
      getAccountMeta(accounts.mintAuthorityPda),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getDepositInstructionDataEncoder().encode(
      args as DepositInstructionDataArgs,
    ),
    programAddress,
  } as DepositInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUserAccountPda,
    TAccountUserAta,
    TAccountLevMint,
    TAccountMintAuthorityPda,
    TAccountTokenProgram
  >);
}

export type DepositInput<
  TAccountUser extends string = string,
  TAccountUserAccountPda extends string = string,
  TAccountUserAta extends string = string,
  TAccountLevMint extends string = string,
  TAccountMintAuthorityPda extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** The user authorizes the deposit into one of their PDAs. */
  user: TransactionSigner<TAccountUser>;
  /** PDA that owns the destination ATA. */
  userAccountPda: Address<TAccountUserAccountPda>;
  /** Destination ATA for this subaccount. */
  userAta: Address<TAccountUserAta>;
  /** Mint for LEV token. */
  levMint: Address<TAccountLevMint>;
  /** Program-derived mint authority PDA. */
  mintAuthorityPda: Address<TAccountMintAuthorityPda>;
  tokenProgram?: Address<TAccountTokenProgram>;
  index: DepositInstructionDataArgs["index"];
  amount: DepositInstructionDataArgs["amount"];
};

export function getDepositInstruction<
  TAccountUser extends string,
  TAccountUserAccountPda extends string,
  TAccountUserAta extends string,
  TAccountLevMint extends string,
  TAccountMintAuthorityPda extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ONCHAIN_PROGRAM_ADDRESS,
>(
  input: DepositInput<
    TAccountUser,
    TAccountUserAccountPda,
    TAccountUserAta,
    TAccountLevMint,
    TAccountMintAuthorityPda,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): DepositInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountUserAccountPda,
  TAccountUserAta,
  TAccountLevMint,
  TAccountMintAuthorityPda,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ONCHAIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    userAccountPda: { value: input.userAccountPda ?? null, isWritable: true },
    userAta: { value: input.userAta ?? null, isWritable: true },
    levMint: { value: input.levMint ?? null, isWritable: true },
    mintAuthorityPda: {
      value: input.mintAuthorityPda ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.userAccountPda),
      getAccountMeta(accounts.userAta),
      getAccountMeta(accounts.levMint),
      getAccountMeta(accounts.mintAuthorityPda),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getDepositInstructionDataEncoder().encode(
      args as DepositInstructionDataArgs,
    ),
    programAddress,
  } as DepositInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUserAccountPda,
    TAccountUserAta,
    TAccountLevMint,
    TAccountMintAuthorityPda,
    TAccountTokenProgram
  >);
}

export type ParsedDepositInstruction<
  TProgram extends string = typeof ONCHAIN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The user authorizes the deposit into one of their PDAs. */
    user: TAccountMetas[0];
    /** PDA that owns the destination ATA. */
    userAccountPda: TAccountMetas[1];
    /** Destination ATA for this subaccount. */
    userAta: TAccountMetas[2];
    /** Mint for LEV token. */
    levMint: TAccountMetas[3];
    /** Program-derived mint authority PDA. */
    mintAuthorityPda: TAccountMetas[4];
    tokenProgram: TAccountMetas[5];
  };
  data: DepositInstructionData;
};

export function parseDepositInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedDepositInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      userAccountPda: getNextAccount(),
      userAta: getNextAccount(),
      levMint: getNextAccount(),
      mintAuthorityPda: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getDepositInstructionDataDecoder().decode(instruction.data),
  };
}
