/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { ONCHAIN_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const EXTERNAL_TRANSFER_DISCRIMINATOR = new Uint8Array([
  11, 179, 85, 190, 61, 53, 105, 169,
]);

export function getExternalTransferDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EXTERNAL_TRANSFER_DISCRIMINATOR,
  );
}

export type ExternalTransferInstruction<
  TProgram extends string = typeof ONCHAIN_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountLevMint extends string | AccountMeta<string> = string,
  TAccountSenderPdaAccount extends string | AccountMeta<string> = string,
  TAccountSenderAta extends string | AccountMeta<string> = string,
  TAccountReceiverPdaAccount extends string | AccountMeta<string> = string,
  TAccountReceiverAtaAccount extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountLevMint extends string
        ? ReadonlyAccount<TAccountLevMint>
        : TAccountLevMint,
      TAccountSenderPdaAccount extends string
        ? ReadonlyAccount<TAccountSenderPdaAccount>
        : TAccountSenderPdaAccount,
      TAccountSenderAta extends string
        ? WritableAccount<TAccountSenderAta>
        : TAccountSenderAta,
      TAccountReceiverPdaAccount extends string
        ? ReadonlyAccount<TAccountReceiverPdaAccount>
        : TAccountReceiverPdaAccount,
      TAccountReceiverAtaAccount extends string
        ? WritableAccount<TAccountReceiverAtaAccount>
        : TAccountReceiverAtaAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ExternalTransferInstructionData = {
  discriminator: ReadonlyUint8Array;
  senderIndex: number;
  receiverAddress: Address;
  amount: bigint;
};

export type ExternalTransferInstructionDataArgs = {
  senderIndex: number;
  receiverAddress: Address;
  amount: number | bigint;
};

export function getExternalTransferInstructionDataEncoder(): FixedSizeEncoder<ExternalTransferInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["senderIndex", getU8Encoder()],
      ["receiverAddress", getAddressEncoder()],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: EXTERNAL_TRANSFER_DISCRIMINATOR }),
  );
}

export function getExternalTransferInstructionDataDecoder(): FixedSizeDecoder<ExternalTransferInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["senderIndex", getU8Decoder()],
    ["receiverAddress", getAddressDecoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getExternalTransferInstructionDataCodec(): FixedSizeCodec<
  ExternalTransferInstructionDataArgs,
  ExternalTransferInstructionData
> {
  return combineCodec(
    getExternalTransferInstructionDataEncoder(),
    getExternalTransferInstructionDataDecoder(),
  );
}

export type ExternalTransferAsyncInput<
  TAccountUser extends string = string,
  TAccountLevMint extends string = string,
  TAccountSenderPdaAccount extends string = string,
  TAccountSenderAta extends string = string,
  TAccountReceiverPdaAccount extends string = string,
  TAccountReceiverAtaAccount extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  levMint: Address<TAccountLevMint>;
  senderPdaAccount: Address<TAccountSenderPdaAccount>;
  senderAta?: Address<TAccountSenderAta>;
  receiverPdaAccount: Address<TAccountReceiverPdaAccount>;
  receiverAtaAccount?: Address<TAccountReceiverAtaAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  senderIndex: ExternalTransferInstructionDataArgs["senderIndex"];
  receiverAddress: ExternalTransferInstructionDataArgs["receiverAddress"];
  amount: ExternalTransferInstructionDataArgs["amount"];
};

export async function getExternalTransferInstructionAsync<
  TAccountUser extends string,
  TAccountLevMint extends string,
  TAccountSenderPdaAccount extends string,
  TAccountSenderAta extends string,
  TAccountReceiverPdaAccount extends string,
  TAccountReceiverAtaAccount extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ONCHAIN_PROGRAM_ADDRESS,
>(
  input: ExternalTransferAsyncInput<
    TAccountUser,
    TAccountLevMint,
    TAccountSenderPdaAccount,
    TAccountSenderAta,
    TAccountReceiverPdaAccount,
    TAccountReceiverAtaAccount,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ExternalTransferInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountLevMint,
    TAccountSenderPdaAccount,
    TAccountSenderAta,
    TAccountReceiverPdaAccount,
    TAccountReceiverAtaAccount,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ONCHAIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    levMint: { value: input.levMint ?? null, isWritable: false },
    senderPdaAccount: {
      value: input.senderPdaAccount ?? null,
      isWritable: false,
    },
    senderAta: { value: input.senderAta ?? null, isWritable: true },
    receiverPdaAccount: {
      value: input.receiverPdaAccount ?? null,
      isWritable: false,
    },
    receiverAtaAccount: {
      value: input.receiverAtaAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.senderAta.value) {
    accounts.senderAta.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.senderPdaAccount.value),
        ),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.levMint.value)),
      ],
    });
  }
  if (!accounts.receiverAtaAccount.value) {
    accounts.receiverAtaAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.receiverPdaAccount.value),
        ),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.levMint.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.levMint),
      getAccountMeta(accounts.senderPdaAccount),
      getAccountMeta(accounts.senderAta),
      getAccountMeta(accounts.receiverPdaAccount),
      getAccountMeta(accounts.receiverAtaAccount),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getExternalTransferInstructionDataEncoder().encode(
      args as ExternalTransferInstructionDataArgs,
    ),
    programAddress,
  } as ExternalTransferInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountLevMint,
    TAccountSenderPdaAccount,
    TAccountSenderAta,
    TAccountReceiverPdaAccount,
    TAccountReceiverAtaAccount,
    TAccountTokenProgram
  >);
}

export type ExternalTransferInput<
  TAccountUser extends string = string,
  TAccountLevMint extends string = string,
  TAccountSenderPdaAccount extends string = string,
  TAccountSenderAta extends string = string,
  TAccountReceiverPdaAccount extends string = string,
  TAccountReceiverAtaAccount extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  levMint: Address<TAccountLevMint>;
  senderPdaAccount: Address<TAccountSenderPdaAccount>;
  senderAta: Address<TAccountSenderAta>;
  receiverPdaAccount: Address<TAccountReceiverPdaAccount>;
  receiverAtaAccount: Address<TAccountReceiverAtaAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  senderIndex: ExternalTransferInstructionDataArgs["senderIndex"];
  receiverAddress: ExternalTransferInstructionDataArgs["receiverAddress"];
  amount: ExternalTransferInstructionDataArgs["amount"];
};

export function getExternalTransferInstruction<
  TAccountUser extends string,
  TAccountLevMint extends string,
  TAccountSenderPdaAccount extends string,
  TAccountSenderAta extends string,
  TAccountReceiverPdaAccount extends string,
  TAccountReceiverAtaAccount extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ONCHAIN_PROGRAM_ADDRESS,
>(
  input: ExternalTransferInput<
    TAccountUser,
    TAccountLevMint,
    TAccountSenderPdaAccount,
    TAccountSenderAta,
    TAccountReceiverPdaAccount,
    TAccountReceiverAtaAccount,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ExternalTransferInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountLevMint,
  TAccountSenderPdaAccount,
  TAccountSenderAta,
  TAccountReceiverPdaAccount,
  TAccountReceiverAtaAccount,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ONCHAIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    levMint: { value: input.levMint ?? null, isWritable: false },
    senderPdaAccount: {
      value: input.senderPdaAccount ?? null,
      isWritable: false,
    },
    senderAta: { value: input.senderAta ?? null, isWritable: true },
    receiverPdaAccount: {
      value: input.receiverPdaAccount ?? null,
      isWritable: false,
    },
    receiverAtaAccount: {
      value: input.receiverAtaAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.levMint),
      getAccountMeta(accounts.senderPdaAccount),
      getAccountMeta(accounts.senderAta),
      getAccountMeta(accounts.receiverPdaAccount),
      getAccountMeta(accounts.receiverAtaAccount),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getExternalTransferInstructionDataEncoder().encode(
      args as ExternalTransferInstructionDataArgs,
    ),
    programAddress,
  } as ExternalTransferInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountLevMint,
    TAccountSenderPdaAccount,
    TAccountSenderAta,
    TAccountReceiverPdaAccount,
    TAccountReceiverAtaAccount,
    TAccountTokenProgram
  >);
}

export type ParsedExternalTransferInstruction<
  TProgram extends string = typeof ONCHAIN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    levMint: TAccountMetas[1];
    senderPdaAccount: TAccountMetas[2];
    senderAta: TAccountMetas[3];
    receiverPdaAccount: TAccountMetas[4];
    receiverAtaAccount: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
  };
  data: ExternalTransferInstructionData;
};

export function parseExternalTransferInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedExternalTransferInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      levMint: getNextAccount(),
      senderPdaAccount: getNextAccount(),
      senderAta: getNextAccount(),
      receiverPdaAccount: getNextAccount(),
      receiverAtaAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getExternalTransferInstructionDataDecoder().decode(instruction.data),
  };
}
