/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { ONCHAIN_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const INTERNAL_TRANSFER_DISCRIMINATOR = new Uint8Array([
  56, 217, 60, 137, 252, 221, 185, 114,
]);

export function getInternalTransferDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INTERNAL_TRANSFER_DISCRIMINATOR,
  );
}

export type InternalTransferInstruction<
  TProgram extends string = typeof ONCHAIN_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountLevMint extends string | AccountMeta<string> = string,
  TAccountSenderAccountPda extends string | AccountMeta<string> = string,
  TAccountSenderAta extends string | AccountMeta<string> = string,
  TAccountReceiverAccountPda extends string | AccountMeta<string> = string,
  TAccountReceiverAta extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountLevMint extends string
        ? WritableAccount<TAccountLevMint>
        : TAccountLevMint,
      TAccountSenderAccountPda extends string
        ? ReadonlyAccount<TAccountSenderAccountPda>
        : TAccountSenderAccountPda,
      TAccountSenderAta extends string
        ? WritableAccount<TAccountSenderAta>
        : TAccountSenderAta,
      TAccountReceiverAccountPda extends string
        ? ReadonlyAccount<TAccountReceiverAccountPda>
        : TAccountReceiverAccountPda,
      TAccountReceiverAta extends string
        ? WritableAccount<TAccountReceiverAta>
        : TAccountReceiverAta,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InternalTransferInstructionData = {
  discriminator: ReadonlyUint8Array;
  senderIndex: number;
  receiverIndex: number;
  amount: bigint;
};

export type InternalTransferInstructionDataArgs = {
  senderIndex: number;
  receiverIndex: number;
  amount: number | bigint;
};

export function getInternalTransferInstructionDataEncoder(): FixedSizeEncoder<InternalTransferInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["senderIndex", getU8Encoder()],
      ["receiverIndex", getU8Encoder()],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INTERNAL_TRANSFER_DISCRIMINATOR }),
  );
}

export function getInternalTransferInstructionDataDecoder(): FixedSizeDecoder<InternalTransferInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["senderIndex", getU8Decoder()],
    ["receiverIndex", getU8Decoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getInternalTransferInstructionDataCodec(): FixedSizeCodec<
  InternalTransferInstructionDataArgs,
  InternalTransferInstructionData
> {
  return combineCodec(
    getInternalTransferInstructionDataEncoder(),
    getInternalTransferInstructionDataDecoder(),
  );
}

export type InternalTransferAsyncInput<
  TAccountUser extends string = string,
  TAccountLevMint extends string = string,
  TAccountSenderAccountPda extends string = string,
  TAccountSenderAta extends string = string,
  TAccountReceiverAccountPda extends string = string,
  TAccountReceiverAta extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  levMint: Address<TAccountLevMint>;
  senderAccountPda: Address<TAccountSenderAccountPda>;
  senderAta?: Address<TAccountSenderAta>;
  receiverAccountPda: Address<TAccountReceiverAccountPda>;
  receiverAta?: Address<TAccountReceiverAta>;
  tokenProgram?: Address<TAccountTokenProgram>;
  senderIndex: InternalTransferInstructionDataArgs["senderIndex"];
  receiverIndex: InternalTransferInstructionDataArgs["receiverIndex"];
  amount: InternalTransferInstructionDataArgs["amount"];
};

export async function getInternalTransferInstructionAsync<
  TAccountUser extends string,
  TAccountLevMint extends string,
  TAccountSenderAccountPda extends string,
  TAccountSenderAta extends string,
  TAccountReceiverAccountPda extends string,
  TAccountReceiverAta extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ONCHAIN_PROGRAM_ADDRESS,
>(
  input: InternalTransferAsyncInput<
    TAccountUser,
    TAccountLevMint,
    TAccountSenderAccountPda,
    TAccountSenderAta,
    TAccountReceiverAccountPda,
    TAccountReceiverAta,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InternalTransferInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountLevMint,
    TAccountSenderAccountPda,
    TAccountSenderAta,
    TAccountReceiverAccountPda,
    TAccountReceiverAta,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ONCHAIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    levMint: { value: input.levMint ?? null, isWritable: true },
    senderAccountPda: {
      value: input.senderAccountPda ?? null,
      isWritable: false,
    },
    senderAta: { value: input.senderAta ?? null, isWritable: true },
    receiverAccountPda: {
      value: input.receiverAccountPda ?? null,
      isWritable: false,
    },
    receiverAta: { value: input.receiverAta ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.senderAta.value) {
    accounts.senderAta.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.senderAccountPda.value),
        ),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.levMint.value)),
      ],
    });
  }
  if (!accounts.receiverAta.value) {
    accounts.receiverAta.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.receiverAccountPda.value),
        ),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.levMint.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.levMint),
      getAccountMeta(accounts.senderAccountPda),
      getAccountMeta(accounts.senderAta),
      getAccountMeta(accounts.receiverAccountPda),
      getAccountMeta(accounts.receiverAta),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getInternalTransferInstructionDataEncoder().encode(
      args as InternalTransferInstructionDataArgs,
    ),
    programAddress,
  } as InternalTransferInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountLevMint,
    TAccountSenderAccountPda,
    TAccountSenderAta,
    TAccountReceiverAccountPda,
    TAccountReceiverAta,
    TAccountTokenProgram
  >);
}

export type InternalTransferInput<
  TAccountUser extends string = string,
  TAccountLevMint extends string = string,
  TAccountSenderAccountPda extends string = string,
  TAccountSenderAta extends string = string,
  TAccountReceiverAccountPda extends string = string,
  TAccountReceiverAta extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  levMint: Address<TAccountLevMint>;
  senderAccountPda: Address<TAccountSenderAccountPda>;
  senderAta: Address<TAccountSenderAta>;
  receiverAccountPda: Address<TAccountReceiverAccountPda>;
  receiverAta: Address<TAccountReceiverAta>;
  tokenProgram?: Address<TAccountTokenProgram>;
  senderIndex: InternalTransferInstructionDataArgs["senderIndex"];
  receiverIndex: InternalTransferInstructionDataArgs["receiverIndex"];
  amount: InternalTransferInstructionDataArgs["amount"];
};

export function getInternalTransferInstruction<
  TAccountUser extends string,
  TAccountLevMint extends string,
  TAccountSenderAccountPda extends string,
  TAccountSenderAta extends string,
  TAccountReceiverAccountPda extends string,
  TAccountReceiverAta extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ONCHAIN_PROGRAM_ADDRESS,
>(
  input: InternalTransferInput<
    TAccountUser,
    TAccountLevMint,
    TAccountSenderAccountPda,
    TAccountSenderAta,
    TAccountReceiverAccountPda,
    TAccountReceiverAta,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InternalTransferInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountLevMint,
  TAccountSenderAccountPda,
  TAccountSenderAta,
  TAccountReceiverAccountPda,
  TAccountReceiverAta,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ONCHAIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    levMint: { value: input.levMint ?? null, isWritable: true },
    senderAccountPda: {
      value: input.senderAccountPda ?? null,
      isWritable: false,
    },
    senderAta: { value: input.senderAta ?? null, isWritable: true },
    receiverAccountPda: {
      value: input.receiverAccountPda ?? null,
      isWritable: false,
    },
    receiverAta: { value: input.receiverAta ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.levMint),
      getAccountMeta(accounts.senderAccountPda),
      getAccountMeta(accounts.senderAta),
      getAccountMeta(accounts.receiverAccountPda),
      getAccountMeta(accounts.receiverAta),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getInternalTransferInstructionDataEncoder().encode(
      args as InternalTransferInstructionDataArgs,
    ),
    programAddress,
  } as InternalTransferInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountLevMint,
    TAccountSenderAccountPda,
    TAccountSenderAta,
    TAccountReceiverAccountPda,
    TAccountReceiverAta,
    TAccountTokenProgram
  >);
}

export type ParsedInternalTransferInstruction<
  TProgram extends string = typeof ONCHAIN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    levMint: TAccountMetas[1];
    senderAccountPda: TAccountMetas[2];
    senderAta: TAccountMetas[3];
    receiverAccountPda: TAccountMetas[4];
    receiverAta: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
  };
  data: InternalTransferInstructionData;
};

export function parseInternalTransferInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInternalTransferInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      levMint: getNextAccount(),
      senderAccountPda: getNextAccount(),
      senderAta: getNextAccount(),
      receiverAccountPda: getNextAccount(),
      receiverAta: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getInternalTransferInstructionDataDecoder().decode(instruction.data),
  };
}
