/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { ONCHAIN_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const WITHDRAW_DISCRIMINATOR = new Uint8Array([
  183, 18, 70, 156, 148, 109, 161, 34,
]);

export function getWithdrawDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(WITHDRAW_DISCRIMINATOR);
}

export type WithdrawInstruction<
  TProgram extends string = typeof ONCHAIN_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountUserAccountPda extends string | AccountMeta<string> = string,
  TAccountUserAta extends string | AccountMeta<string> = string,
  TAccountLevMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountUserAccountPda extends string
        ? ReadonlyAccount<TAccountUserAccountPda>
        : TAccountUserAccountPda,
      TAccountUserAta extends string
        ? WritableAccount<TAccountUserAta>
        : TAccountUserAta,
      TAccountLevMint extends string
        ? WritableAccount<TAccountLevMint>
        : TAccountLevMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type WithdrawInstructionData = {
  discriminator: ReadonlyUint8Array;
  index: number;
  amount: bigint;
};

export type WithdrawInstructionDataArgs = {
  index: number;
  amount: number | bigint;
};

export function getWithdrawInstructionDataEncoder(): FixedSizeEncoder<WithdrawInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["index", getU8Encoder()],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: WITHDRAW_DISCRIMINATOR }),
  );
}

export function getWithdrawInstructionDataDecoder(): FixedSizeDecoder<WithdrawInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["index", getU8Decoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getWithdrawInstructionDataCodec(): FixedSizeCodec<
  WithdrawInstructionDataArgs,
  WithdrawInstructionData
> {
  return combineCodec(
    getWithdrawInstructionDataEncoder(),
    getWithdrawInstructionDataDecoder(),
  );
}

export type WithdrawAsyncInput<
  TAccountUser extends string = string,
  TAccountUserAccountPda extends string = string,
  TAccountUserAta extends string = string,
  TAccountLevMint extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  userAccountPda: Address<TAccountUserAccountPda>;
  userAta?: Address<TAccountUserAta>;
  levMint: Address<TAccountLevMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  index: WithdrawInstructionDataArgs["index"];
  amount: WithdrawInstructionDataArgs["amount"];
};

export async function getWithdrawInstructionAsync<
  TAccountUser extends string,
  TAccountUserAccountPda extends string,
  TAccountUserAta extends string,
  TAccountLevMint extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ONCHAIN_PROGRAM_ADDRESS,
>(
  input: WithdrawAsyncInput<
    TAccountUser,
    TAccountUserAccountPda,
    TAccountUserAta,
    TAccountLevMint,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  WithdrawInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUserAccountPda,
    TAccountUserAta,
    TAccountLevMint,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ONCHAIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    userAccountPda: { value: input.userAccountPda ?? null, isWritable: false },
    userAta: { value: input.userAta ?? null, isWritable: true },
    levMint: { value: input.levMint ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.userAta.value) {
    accounts.userAta.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.userAccountPda.value),
        ),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.levMint.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.userAccountPda),
      getAccountMeta(accounts.userAta),
      getAccountMeta(accounts.levMint),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getWithdrawInstructionDataEncoder().encode(
      args as WithdrawInstructionDataArgs,
    ),
    programAddress,
  } as WithdrawInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUserAccountPda,
    TAccountUserAta,
    TAccountLevMint,
    TAccountTokenProgram
  >);
}

export type WithdrawInput<
  TAccountUser extends string = string,
  TAccountUserAccountPda extends string = string,
  TAccountUserAta extends string = string,
  TAccountLevMint extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  userAccountPda: Address<TAccountUserAccountPda>;
  userAta: Address<TAccountUserAta>;
  levMint: Address<TAccountLevMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  index: WithdrawInstructionDataArgs["index"];
  amount: WithdrawInstructionDataArgs["amount"];
};

export function getWithdrawInstruction<
  TAccountUser extends string,
  TAccountUserAccountPda extends string,
  TAccountUserAta extends string,
  TAccountLevMint extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ONCHAIN_PROGRAM_ADDRESS,
>(
  input: WithdrawInput<
    TAccountUser,
    TAccountUserAccountPda,
    TAccountUserAta,
    TAccountLevMint,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): WithdrawInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountUserAccountPda,
  TAccountUserAta,
  TAccountLevMint,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ONCHAIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    userAccountPda: { value: input.userAccountPda ?? null, isWritable: false },
    userAta: { value: input.userAta ?? null, isWritable: true },
    levMint: { value: input.levMint ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.userAccountPda),
      getAccountMeta(accounts.userAta),
      getAccountMeta(accounts.levMint),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getWithdrawInstructionDataEncoder().encode(
      args as WithdrawInstructionDataArgs,
    ),
    programAddress,
  } as WithdrawInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUserAccountPda,
    TAccountUserAta,
    TAccountLevMint,
    TAccountTokenProgram
  >);
}

export type ParsedWithdrawInstruction<
  TProgram extends string = typeof ONCHAIN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    userAccountPda: TAccountMetas[1];
    userAta: TAccountMetas[2];
    levMint: TAccountMetas[3];
    tokenProgram: TAccountMetas[4];
  };
  data: WithdrawInstructionData;
};

export function parseWithdrawInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedWithdrawInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      userAccountPda: getNextAccount(),
      userAta: getNextAccount(),
      levMint: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getWithdrawInstructionDataDecoder().decode(instruction.data),
  };
}
