/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { ONCHAIN_PROGRAM_ADDRESS } from "../programs";

/** InsufficientFunds: Insufficient funds for the amount requested */
export const ONCHAIN_ERROR__INSUFFICIENT_FUNDS = 0x1770; // 6000
/** CannotTransferTokensBetweenSameAccounts: Cannot transfer tokens between two accounts with the same id. That is basically the same account */
export const ONCHAIN_ERROR__CANNOT_TRANSFER_TOKENS_BETWEEN_SAME_ACCOUNTS = 0x1771; // 6001

export type OnchainError =
  | typeof ONCHAIN_ERROR__CANNOT_TRANSFER_TOKENS_BETWEEN_SAME_ACCOUNTS
  | typeof ONCHAIN_ERROR__INSUFFICIENT_FUNDS;

let onchainErrorMessages: Record<OnchainError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  onchainErrorMessages = {
    [ONCHAIN_ERROR__CANNOT_TRANSFER_TOKENS_BETWEEN_SAME_ACCOUNTS]: `Cannot transfer tokens between two accounts with the same id. That is basically the same account`,
    [ONCHAIN_ERROR__INSUFFICIENT_FUNDS]: `Insufficient funds for the amount requested`,
  };
}

export function getOnchainErrorMessage(code: OnchainError): string {
  if (process.env.NODE_ENV !== "production") {
    return (onchainErrorMessages as Record<OnchainError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isOnchainError<TProgramErrorCode extends OnchainError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    ONCHAIN_PROGRAM_ADDRESS,
    code,
  );
}
